package com.lhfeiyu.tech.blog.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * Article
 *
 * @author lhfeiyu
 * @created Create Time: Wed Jul 03 18:30:05 CST 2019
 */
@ApiModel(value = "com.lhfeiyu.tech.blog.model.Article", description = "文章表")
@Data
public class Article extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.user_id
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 用户ID
     */
    @ApiModelProperty(value = "用户ID", name = "userId")
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.title
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 标题
     */
    @ApiModelProperty(value = "标题", name = "title")
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.subhead
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 副标题
     */
    @ApiModelProperty(value = "副标题", name = "subhead")
    private String subhead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.description
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 描述
     */
    @ApiModelProperty(value = "描述", name = "description")
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.url
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 内容文件链接
     */
    @ApiModelProperty(value = "内容文件链接", name = "url")
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.state
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 状态：1.正常 2.停用 3.异常 99.删除
     */
    @ApiModelProperty(value = "状态：1.正常 2.停用 3.异常 99.删除", name = "state")
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.type
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 类型：1.本人创建 2.转载 3.后台创建
     */
    @ApiModelProperty(value = "类型：1.本人创建 2.转载 3.后台创建", name = "type")
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.rank
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 等级：与权重对应，从低到高
     */
    @ApiModelProperty(value = "等级：与权重对应，从低到高", name = "rank")
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.allow_comment
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 是否允许评论
     */
    @ApiModelProperty(value = "是否允许评论", name = "allowComment")
    private Boolean allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.allow_reprint
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 是否允许转载
     */
    @ApiModelProperty(value = "是否允许转载", name = "allowReprint")
    private Boolean allowReprint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_article.content
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 内容
     */
    @ApiModelProperty(value = "内容", name = "content")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tech_article
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    private static final long serialVersionUID = 1L;
}