package com.lhfeiyu.tech.blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Category
 *
 * @author lhfeiyu
 * @created Create Time: Wed Jul 03 18:30:05 CST 2019
 */
@ApiModel(value = "com.lhfeiyu.tech.blog.model.Category", description = "分类表")
@Data
public class Category extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 父节点系统编号
     */
    @ApiModelProperty(value = "父节点系统编号", name = "parentId")
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 分类名称
     */
    @ApiModelProperty(value = "分类名称", name = "categoryName")
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.priority
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 排序优先级
     */
    @ApiModelProperty(value = "排序优先级", name = "priority")
    private Short priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.status
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 状态
     */
    @ApiModelProperty(value = "状态", name = "status")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_date
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 创建时间
     */
    @ApiModelProperty(value = "创建时间", name = "createDate")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.edit_date
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 编辑时间
     */
    @ApiModelProperty(value = "编辑时间", name = "editDate")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
    private Date editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    private static final long serialVersionUID = 1L;
}