package com.lhfeiyu.tech.blog.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

/**
 * Category
 *
 * @author lhfeiyu
 * @created Create Time: Mon Jun 17 23:58:16 CST 2019
 */
@ApiModel(value = "com.lhfeiyu.tech.blog.model.Category", description = "")
@Data
public class Category extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parent_id
     *
     * @mbg.generated Mon Jun 17 23:58:16 CST 2019
     */
    /**
     * 父节点系统编号
     */
    @ApiModelProperty(value = "父节点系统编号", name = "parentId")
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated Mon Jun 17 23:58:16 CST 2019
     */
    /**
     * 分类名称
     */
    @ApiModelProperty(value = "分类名称", name = "categoryName")
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.priority
     *
     * @mbg.generated Mon Jun 17 23:58:16 CST 2019
     */
    /**
     * 排序优先级
     */
    @ApiModelProperty(value = "排序优先级", name = "priority")
    private Short priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated Mon Jun 17 23:58:16 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Mon Jun 17 23:58:16 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parentId=").append(parentId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", priority=").append(priority);
        sb.append("]");
        return sb.toString();
    }
}