package com.lhfeiyu.tech.blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * LoginLog
 *
 * @author lhfeiyu
 * @created Create Time: Wed Jul 03 18:30:05 CST 2019
 */
@ApiModel(value = "com.lhfeiyu.tech.blog.model.LoginLog", description = "登录日志表")
@Data
public class LoginLog extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_login_log.user_id
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 用户ID
     */
    @ApiModelProperty(value = "用户ID", name = "userId")
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_login_log.user_name
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 用户名
     */
    @ApiModelProperty(value = "用户名", name = "userName")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_login_log.account
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 账号
     */
    @ApiModelProperty(value = "账号", name = "account")
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_login_log.login_ip
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 登录IP
     */
    @ApiModelProperty(value = "登录IP", name = "loginIp")
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_login_log.login_time
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 登录时间
     */
    @ApiModelProperty(value = "登录时间", name = "loginTime")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    private static final long serialVersionUID = 1L;
}