package com.lhfeiyu.tech.blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * User
 *
 * @author lhfeiyu
 * @created Create Time: Wed Jul 03 18:30:05 CST 2019
 */
@ApiModel(value = "com.lhfeiyu.tech.blog.model.User", description = "用户表")
@Data
public class User extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.user_name
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 昵称
     */
    @ApiModelProperty(value = "昵称", name = "userName")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.real_name
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 真实姓名
     */
    @ApiModelProperty(value = "真实姓名", name = "realName")
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.phone
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 手机
     */
    @ApiModelProperty(value = "手机", name = "phone")
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.email
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 邮箱
     */
    @ApiModelProperty(value = "邮箱", name = "email")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.id_card
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 身份证
     */
    @ApiModelProperty(value = "身份证", name = "idCard")
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.password
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 密码
     */
    @ApiModelProperty(value = "密码", name = "password")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.state
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 状态：1.正常 2.停用 3.异常 99.删除
     */
    @ApiModelProperty(value = "状态：1.正常 2.停用 3.异常 99.删除", name = "state")
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.type
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 类型：1.普通用户 2.测试用户
     */
    @ApiModelProperty(value = "类型：1.普通用户 2.测试用户", name = "type")
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.rank
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 等级：1.普通 2.VIP1 3.VIP2
     */
    @ApiModelProperty(value = "等级：1.普通 2.VIP1 3.VIP2", name = "rank")
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.sex
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 性别：1.未知 2.男 3.女 4.保密
     */
    @ApiModelProperty(value = "性别：1.未知 2.男 3.女 4.保密", name = "sex")
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.birthday
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 生日
     */
    @ApiModelProperty(value = "生日", name = "birthday")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.province
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 省
     */
    @ApiModelProperty(value = "省", name = "province")
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.city
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 市
     */
    @ApiModelProperty(value = "市", name = "city")
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.address
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 地址
     */
    @ApiModelProperty(value = "地址", name = "address")
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.avatar
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 头像地址
     */
    @ApiModelProperty(value = "头像地址", name = "avatar")
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.qr_code
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 个人二维码
     */
    @ApiModelProperty(value = "个人二维码", name = "qrCode")
    private String qrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.url
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 个人主页
     */
    @ApiModelProperty(value = "个人主页", name = "url")
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_user.introduction
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    /**
     * 简介
     */
    @ApiModelProperty(value = "简介", name = "introduction")
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tech_user
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    private static final long serialVersionUID = 1L;
}