package com.lhfeiyu.tech.blog.mapper;

import com.lhfeiyu.tech.blog.model.LoginLog;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

/**
 * LoginLogMapper
 *
 * @author lhfeiyu
 * @created Create Time: Wed Jul 03 18:30:05 CST 2019
 */
@Mapper
@Component
public interface LoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    int insert(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    int insertSelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    LoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    int updateByPrimaryKeySelective(LoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_login_log
     *
     * @mbg.generated Wed Jul 03 18:30:05 CST 2019
     */
    int updateByPrimaryKey(LoginLog record);
}