server:
    port: 8888
    error:
        path: /custom/error
    tomcat:
        uri-encoding: utf-8
        resource:
            cache-ttl: 0
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.lhfeiyu.tech.mapper.model
    mapper-locations: classpath*:com.lhfeiyu.tech.blog.mapper/*.xml
logging:
    config: classpath:logback.xml
eureka:
    client:
        serviceUrl:
            defaultZone: http://182.61.49.180:8761/eureka/
spring:
    application:
        name: tech-blog-provider
    main:
        allow-bean-definition-overriding: true
    datasource:
        name: druidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/tech_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        url: jdbc:mysql://182.61.49.180:3306/tech_share?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: lh
        password: Keep123!
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    servlet:
        multipart:
            enabled: true
            max-request-size: 10000
    thymeleaf:
        enabled: false
        cache: false
    resources:
        chain:
            cache: false
            strategy:
                content:
                    enabled: true
                    paths: /static/**
        cache:
            period: 0
            cachecontrol:
                no-cache: true
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
        add-properties: true
    mvc:
        static-path-pattern: /resources/static/**
    rabbitmq:
        host: 182.61.49.180
        port: 5672
        username: lh_blog
        password: keep123!
        cache:
            connection:
                mode: channel
    cloud:
        bus:
            trace:
                enabled: true
    sleuth:
        baggage-keys:
        - SessionId
management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
airson:
    hello: 2
